### ISSUE TITLE
zendisc.conf missed by updateConfigs

### ISSUE THREAD

**Issue by krull** [epuzanov/ZenPacks.community.DistributedCollectors#11]
FYI I had to manually edit zendisc.conf to add the monitor and hubhost.

Also hubusername and hubpassword isn't updated on all conf files.

**Comment by mhaswell-resilient** [comment]
Please don't open new issues for the same problem - replying to previous issue at https://github.com/epuzanov/ZenPacks.community.DistributedCollectors/issues/10
